# Build Stage
FROM node:16.0.0-alpine as build-stage

ARG NPM_VERSION=8.0.0

RUN npm install -g npm@${NPM_VERSION}

RUN npm install -g json-server

COPY products.json .

EXPOSE 3001

CMD ["json-server", "--watch", "products.json", "--port", "3001", "--host", "0.0.0.0"]
